version: '3.1'

services:

  mongo-db:
    image: mongo
    container_name: smart-home-db
    restart: always
    environment:
      MONGO_INITDB_DATABASE: SmartHomeDB
    # Uncomment this if you want to access database from outside the Docker network
    # ports:
    #   - "27017:27017"
    volumes:
      - ./express-backend/dbconfiguration.mongodb.js:/setup/dbconfiguration.mongodb.js
    networks:
      - containers-net 

  express-server:
    image: node
    container_name: smart-home-express
    restart: always
    volumes:
      - ./express-backend:/express/
    working_dir: /express/ 
    command: ["sh", "-c", "npm install && node serverExpress.js"]
    ports:
      - "3000:3000"
    networks:
      - containers-net

  frontend:
    image: node
    container_name: smart-home-front
    restart: always
    volumes:
      - ./smarthome-app:/front/
    working_dir: /front/
    command: ["sh", "-c", "npm install && npm run build && npm start"]
    ports:
      - "8080:8080"
